name: flutter_spectrogram
description: A Flutter project to plot Spectrogram. Mainly used by PraatMobile
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  fftea: ^1.5.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  wav: ^1.3.0
  scidart: ^0.0.2-dev.12
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/