name: flutter_spectrogram
description: A Flutter project to plot Spectrogram. Mainly used by PraatMobile
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  fftea: ^1.5.0
  quiver: ^3.2.1
  wav: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0